git_repository(
  name = "protobuf",
  remote = "https://github.com/google/protobuf",
  commit = "80a37e0782d2d702d52234b62dd4b9ec74fd2c95" #v3.4.1
)

new_http_archive(
  name = "gtest",
  url = "https://github.com/google/googletest/archive/release-1.7.0.zip",
  sha256 = "b58cb7547a28b2c718d1e38aee18a3659c9e3ff52440297e965f5edffe34b6d0",
  build_file = "gtest.BUILD",
  strip_prefix = "googletest-release-1.7.0",
)