// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/event_test.proto
#pragma warning disable 1591, 0612, 3021, 162
#region Designer generated code

using System;
using System.IO;
using System.Collections.Generic;
using Google.Protobuf;
using global::Zynga.Protobuf.Runtime;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
using zpr = global::Zynga.Protobuf.Runtime;
namespace Com.Zynga.Runtime.Protobuf {

  /// <summary>Holder for reflection information generated from test/event_test.proto</summary>
  public static partial class EventTestReflection {

    #region Descriptor
    /// <summary>File descriptor for test/event_test.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EventTestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChV0ZXN0L2V2ZW50X3Rlc3QucHJvdG8SGmNvbS56eW5nYS5ydW50aW1lLnBy",
            "b3RvYnVmGhJldmVudF9wbHVnaW4ucHJvdG8aH2dvb2dsZS9wcm90b2J1Zi90",
            "aW1lc3RhbXAucHJvdG8iIQoLVGVzdE1lc3NhZ2USEgoEZGF0YRgBIAEoBVIE",
            "ZGF0YSIqCg5UZXN0VHdvTWVzc2FnZRISCgRkYXRhGAEgASgFUgRkYXRhOgTI",
            "uB4BIpsKCglFdmVudFRlc3QSGAoHZXZlbnRJZBgBIAEoCVIHZXZlbnRJZBIS",
            "CgNmb28YAiABKAlIAFIDZm9vElEKCGludGVybmFsGAMgASgLMjMuY29tLnp5",
            "bmdhLnJ1bnRpbWUucHJvdG9idWYuRXZlbnRUZXN0Lk5lc3RlZE1lc3NhZ2VI",
            "AFIIaW50ZXJuYWwSQwoKdGVzdF9ldmVudBgEIAEoDjIkLmNvbS56eW5nYS5y",
            "dW50aW1lLnByb3RvYnVmLkVudW1UZXN0Ugl0ZXN0RXZlbnQSGwoJdGVzdF9w",
            "cmltGAUgAygFUgh0ZXN0UHJpbRJWCgx0ZXN0X21lc3NhZ2UYBiADKAsyMy5j",
            "b20uenluZ2EucnVudGltZS5wcm90b2J1Zi5FdmVudFRlc3QuTmVzdGVkTWVz",
            "c2FnZVILdGVzdE1lc3NhZ2USQQoJdGVzdF9lbnVtGAcgAygOMiQuY29tLnp5",
            "bmdhLnJ1bnRpbWUucHJvdG9idWYuRW51bVRlc3RSCHRlc3RFbnVtEk0KCHRl",
            "c3RfbWFwGAggAygLMjIuY29tLnp5bmdhLnJ1bnRpbWUucHJvdG9idWYuRXZl",
            "bnRUZXN0LlRlc3RNYXBFbnRyeVIHdGVzdE1hcBJICgRkYXRhGAkgASgLMjQu",
            "Y29tLnp5bmdhLnJ1bnRpbWUucHJvdG9idWYuRXZlbnRUZXN0LkV2ZW50T25l",
            "b2ZUZXN0UgRkYXRhElcKDHRlc3RfbWFwX3R3bxgKIAMoCzI1LmNvbS56eW5n",
            "YS5ydW50aW1lLnByb3RvYnVmLkV2ZW50VGVzdC5UZXN0TWFwVHdvRW50cnlS",
            "CnRlc3RNYXBUd28SUQoQdGVzdF9ub25fbWVzc2FnZRgLIAEoCzInLmNvbS56",
            "eW5nYS5ydW50aW1lLnByb3RvYnVmLlRlc3RNZXNzYWdlUg50ZXN0Tm9uTWVz",
            "c2FnZRI7Chd0ZXN0X3N0cmluZ19ub19jaGVja3N1bRgMIAEoCUIE0LgeAVIU",
            "dGVzdFN0cmluZ05vQ2hlY2tzdW0SKAoQdGVzdF9ieXRlc19maWVsZBgNIAEo",
            "DFIOdGVzdEJ5dGVzRmllbGQSLgoEZGF0ZRgOIAEoCzIaLmdvb2dsZS5wcm90",
            "b2J1Zi5UaW1lc3RhbXBSBGRhdGUaaQoNTmVzdGVkTWVzc2FnZRISCgRkYXRh",
            "GAEgASgFUgRkYXRhEkQKB2RhdGFUd28YAiABKAsyKi5jb20uenluZ2EucnVu",
            "dGltZS5wcm90b2J1Zi5UZXN0VHdvTWVzc2FnZVIHZGF0YVR3bxqFAQoORXZl",
            "bnRPbmVvZlRlc3QSEgoDZm9vGAEgASgJSABSA2ZvbxJRCghpbnRlcm5hbBgC",
            "IAEoCzIzLmNvbS56eW5nYS5ydW50aW1lLnByb3RvYnVmLkV2ZW50VGVzdC5O",
            "ZXN0ZWRNZXNzYWdlSABSCGludGVybmFsOgTIuB4BQgYKBGJvZHkabwoMVGVz",
            "dE1hcEVudHJ5EhAKA2tleRgBIAEoCVIDa2V5EkkKBXZhbHVlGAIgASgLMjMu",
            "Y29tLnp5bmdhLnJ1bnRpbWUucHJvdG9idWYuRXZlbnRUZXN0Lk5lc3RlZE1l",
            "c3NhZ2VSBXZhbHVlOgI4ARo9Cg9UZXN0TWFwVHdvRW50cnkSEAoDa2V5GAEg",
            "ASgFUgNrZXkSFAoFdmFsdWUYAiABKAlSBXZhbHVlOgI4AToEyLgeAUILCgl0",
            "ZXN0T25lb2YqJAoIRW51bVRlc3QSCQoFVkFMVUUQABINCglWQUxVRV9UV08Q",
            "AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zynga.Protobuf.EventSource.EventPluginReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Com.Zynga.Runtime.Protobuf.EnumTest), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Zynga.Runtime.Protobuf.TestMessage), global::Com.Zynga.Runtime.Protobuf.TestMessage.Parser, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Zynga.Runtime.Protobuf.TestTwoMessage), global::Com.Zynga.Runtime.Protobuf.TestTwoMessage.Parser, new[]{ "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Zynga.Runtime.Protobuf.EventTest), global::Com.Zynga.Runtime.Protobuf.EventTest.Parser, new[]{ "EventId", "Foo", "Internal", "TestEvent", "TestPrim", "TestMessage", "TestEnum", "TestMap", "Data", "TestMapTwo", "TestNonMessage", "TestStringNoChecksum", "TestBytesField", "Date" }, new[]{ "TestOneof" }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage), global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage.Parser, new[]{ "Data", "DataTwo" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest), global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest.Parser, new[]{ "Foo", "Internal" }, new[]{ "Body" }, null, null),
            null, null, })
          }));
    }
    #endregion

  }
  #region Enums
  public enum EnumTest {
    [pbr::OriginalName("VALUE")] Value = 0,
    [pbr::OriginalName("VALUE_TWO")] ValueTwo = 1,
  }

  #endregion

  #region Messages
  public sealed partial class TestMessage : pb::IMessage<TestMessage> {
    private static readonly pb::MessageParser<TestMessage> _parser = new pb::MessageParser<TestMessage>(() => new TestMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Zynga.Runtime.Protobuf.EventTestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestMessage(TestMessage other) : this() {
      data_ = other.data_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestMessage Clone() {
      return new TestMessage(this);
    }

    public static bool IsEventSourced = false;

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private int data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Data {
      get { return data_; }
      set {
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data != 0) hash ^= Data.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void GetChecksum(BinaryWriter inWriter) {
      if (Data != 0) inWriter.Write(Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestMessage other) {
      if (other == null) {
        return;
      }
      if (other.Data != 0) {
        Data = other.Data;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Data = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// must flag internal message as event_sourced
  /// </summary>
  public sealed partial class TestTwoMessage : zpr::EventRegistry, pb::IMessage<TestTwoMessage> {
    private static readonly pb::MessageParser<TestTwoMessage> _parser = new pb::MessageParser<TestTwoMessage>(() => new TestTwoMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestTwoMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Zynga.Runtime.Protobuf.EventTestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestTwoMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestTwoMessage(TestTwoMessage other) : this() {
      data_ = other.data_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestTwoMessage Clone() {
      return new TestTwoMessage(this);
    }

    public static bool IsEventSourced = true;

    public override void SetParent(EventContext parent, EventPath path) {
      base.SetParent(parent, path);
    }
    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 1;
    private int data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Data {
      get { return data_; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(1, new zpr.EventSource.EventContent { I32 = value });
        #endif
        data_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestTwoMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestTwoMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Data != other.Data) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Data != 0) hash ^= Data.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void GetChecksum(BinaryWriter inWriter) {
      if (Data != 0) inWriter.Write(Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Data != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Data != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestTwoMessage other) {
      if (other == null) {
        return;
      }
      if (other.Data != 0) {
        Data = other.Data;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Data = input.ReadInt32();
            break;
          }
        }
      }
    }

    public override bool ApplyEvent(zpr.EventSource.EventData e, int pathIndex) {
        if (e.Path.Count == 0) {
          this.MergeFrom(e.Set.ByteData);
          return true;
        }
        switch (e.Path[pathIndex]) {
          case 1: {
            data_ = e.Set.I32;
          }
          break;
          default: 
            return false;
          break;
        }
      return true;
    }

    public zpr.EventSource.EventSourceRoot GenerateSnapshot() {
      var er = new zpr.EventSource.EventSourceRoot();
      var setEvent = new zpr.EventSource.EventData {
        Set = new zpr.EventSource.EventContent {
          ByteData = this.ToByteString()
        }
      };
      er.Events.Add(setEvent);
      return er;
    }

  }

  public sealed partial class EventTest : zpr::EventRegistry, pb::IMessage<EventTest> {
    private static readonly pb::MessageParser<EventTest> _parser = new pb::MessageParser<EventTest>(() => new EventTest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EventTest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Zynga.Runtime.Protobuf.EventTestReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventTest() {
      OnConstruction();
      testPrim_.SetContext(Context, 5);
      testMessage_.SetContext(Context, 6);
      testEnum_.SetContext(Context, 7);
      testMap_.SetContext(Context, 8);
      testMapTwo_.SetContext(Context, 10);
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventTest(EventTest other) : this() {
      eventId_ = other.eventId_;
      testEvent_ = other.testEvent_;
      testPrim_ = new EventRepeatedField<int>(testPrimDataConverter, other.TestPrim.Clone());
      testPrim_.SetContext(Context, 5);
      testMessage_ = new EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>(testMessageDataConverter, other.TestMessage.Clone(), true);
      testMessage_.SetContext(Context, 6);
      testEnum_ = new EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EnumTest>(testEnumDataConverter, other.TestEnum.Clone());
      testEnum_.SetContext(Context, 7);
      testMap_ = new EventMapField<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>(testMapMapConverter, other.testMap_.Clone(), true);
      testMap_.SetContext(Context, 8);
      data_ = other.data_ != null ? other.Data.Clone() : null;
      testMapTwo_ = new EventMapField<int, string>(testMapTwoMapConverter, other.testMapTwo_.Clone());
      testMapTwo_.SetContext(Context, 10);
      testNonMessage_ = other.testNonMessage_ != null ? other.TestNonMessage.Clone() : null;
      testStringNoChecksum_ = other.testStringNoChecksum_;
      testBytesField_ = other.testBytesField_;
      date_ = other.date_ != null ? other.Date.Clone() : null;
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.Foo:
          Foo = other.Foo;
          break;
        case TestOneofOneofCase.Internal:
          Internal = other.Internal.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventTest Clone() {
      return new EventTest(this);
    }

    public static bool IsEventSourced = true;

    public override void SetParent(EventContext parent, EventPath path) {
      base.SetParent(parent, path);
      testPrim_.SetContext(Context, 5);
      testMessage_.SetContext(Context, 6);
      testEnum_.SetContext(Context, 7);
      testMap_.SetContext(Context, 8);
      testMapTwo_.SetContext(Context, 10);
    }
    /// <summary>Field number for the "eventId" field.</summary>
    public const int EventIdFieldNumber = 1;
    private string eventId_ = "";
    /// <summary>
    /// unique event identifier
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EventId {
      get { return eventId_; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(1, new zpr.EventSource.EventContent { StringData = pb::ProtoPreconditions.CheckNotNull(value, "value") });
        #endif
        eventId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "foo" field.</summary>
    public const int FooFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Foo {
      get { return testOneofCase_ == TestOneofOneofCase.Foo ? (string) testOneof_ : ""; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(2, new zpr.EventSource.EventContent { StringData = pb::ProtoPreconditions.CheckNotNull(value, "value") });
        #endif
        testOneof_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        testOneofCase_ = TestOneofOneofCase.Foo;
      }
    }

    /// <summary>Field number for the "internal" field.</summary>
    public const int InternalFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage Internal {
      get { return testOneofCase_ == TestOneofOneofCase.Internal ? (global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage) testOneof_ : null; }
      set {
        if(testOneof_ != null) ((global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage) testOneof_).ClearParent();
        value.SetParent(Context, new EventPath(Context.Path, 3));
        #if !DISABLE_EVENTS
        Context.AddSetEvent(3, new zpr.EventSource.EventContent { ByteData = value.ToByteString() });
        #endif
        testOneof_ = value;
        testOneofCase_ = value == null ? TestOneofOneofCase.None : TestOneofOneofCase.Internal;
      }
    }

    /// <summary>Field number for the "test_event" field.</summary>
    public const int TestEventFieldNumber = 4;
    private global::Com.Zynga.Runtime.Protobuf.EnumTest testEvent_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Zynga.Runtime.Protobuf.EnumTest TestEvent {
      get { return testEvent_; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(4, new zpr.EventSource.EventContent { U32 = (uint) value });
        #endif
        testEvent_ = value;
      }
    }

    /// <summary>Field number for the "test_prim" field.</summary>
    public const int TestPrimFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_testPrim_codec
        = pb::FieldCodec.ForInt32(42);
    public class TestPrimDataConverter: EventDataConverter<int> {
      public override zpr.EventSource.EventContent GetEventData(int data) {
        return new zpr.EventSource.EventContent() { data_ = data, dataCase_ = zpr.EventSource.EventContent.DataOneofCase.I32 };
      }
      public override int GetItem(zpr.EventSource.EventContent data) {
        return data.I32;
      }
    }
    private static TestPrimDataConverter testPrimDataConverter = new TestPrimDataConverter();
    private readonly EventRepeatedField<int> testPrim_ = new EventRepeatedField<int>(testPrimDataConverter);
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventRepeatedField<int> TestPrim {
      get { return testPrim_; }
    }

    /// <summary>Field number for the "test_message" field.</summary>
    public const int TestMessageFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> _repeated_testMessage_codec
        = pb::FieldCodec.ForMessage(50, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage.Parser);
    public class TestMessageDataConverter: EventDataConverter<global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> {
      public override zpr.EventSource.EventContent GetEventData(global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage data) {
        var byteData = (data as pb::IMessage)?.ToByteString();
        return new zpr.EventSource.EventContent() { ByteData = byteData };
      }
      public override global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage GetItem(zpr.EventSource.EventContent data) {
        return global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage.Parser.ParseFrom(data.ByteData);
      }
    }
    private static TestMessageDataConverter testMessageDataConverter = new TestMessageDataConverter();
    private readonly EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> testMessage_ = new EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>(testMessageDataConverter, true);
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> TestMessage {
      get { return testMessage_; }
    }

    /// <summary>Field number for the "test_enum" field.</summary>
    public const int TestEnumFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Com.Zynga.Runtime.Protobuf.EnumTest> _repeated_testEnum_codec
        = pb::FieldCodec.ForEnum(58, x => (int) x, x => (global::Com.Zynga.Runtime.Protobuf.EnumTest) x);
    public class TestEnumDataConverter: EventDataConverter<global::Com.Zynga.Runtime.Protobuf.EnumTest> {
      public override zpr.EventSource.EventContent GetEventData(global::Com.Zynga.Runtime.Protobuf.EnumTest data) {
        return new zpr.EventSource.EventContent() { data_ = Convert.ToUInt32(data), dataCase_ = zpr.EventSource.EventContent.DataOneofCase.U32 };
      }
      public override global::Com.Zynga.Runtime.Protobuf.EnumTest GetItem(zpr.EventSource.EventContent data) {
        return (global::Com.Zynga.Runtime.Protobuf.EnumTest) data.U32;
      }
    }
    private static TestEnumDataConverter testEnumDataConverter = new TestEnumDataConverter();
    private readonly EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EnumTest> testEnum_ = new EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EnumTest>(testEnumDataConverter);
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventRepeatedField<global::Com.Zynga.Runtime.Protobuf.EnumTest> TestEnum {
      get { return testEnum_; }
    }

    /// <summary>Field number for the "test_map" field.</summary>
    public const int TestMapFieldNumber = 8;
    private static readonly pbc::MapField<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>.Codec _map_testMap_codec
        = new pbc::MapField<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>.Codec(pb::FieldCodec.ForString(10), pb::FieldCodec.ForMessage(18, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage.Parser), 66);
    internal class TestMapMapConverter : EventMapConverter<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> {
      public override ByteString GetKeyValue(string key, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage value, bool skipValue = false) {
        using (var memStream = new MemoryStream()) {
          var dataStream = new CodedOutputStream(memStream);
          dataStream.WriteString(key);
          if(!skipValue) dataStream.WriteMessage(value);
          dataStream.Flush();
          return ByteString.CopyFrom(memStream.ToArray());
        }
      }
      public override KeyValuePair<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> GetItem(ByteString data, bool skipValue = false) {
        var dataStream = data.CreateCodedInput();
        var realKeytestMap = dataStream.ReadString();
        if (skipValue) {
          return new KeyValuePair<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>(realKeytestMap, default(global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage));
        }
        else {
          var realValuetestMap = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage();
          dataStream.ReadMessage(realValuetestMap);;
          return new KeyValuePair<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>(realKeytestMap, realValuetestMap);
        }
      }
    }
    private static readonly EventMapConverter<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> testMapMapConverter = new TestMapMapConverter();
    private readonly EventMapField<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> testMap_ = new EventMapField<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage>(testMapMapConverter, true);
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventMapField<string, global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage> TestMap {
      get { return testMap_; }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 9;
    private global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest Data {
      get { return data_; }
      set {
        if(data_ != null) data_.ClearParent();
        value.SetParent(Context, new EventPath(Context.Path, 9));
        #if !DISABLE_EVENTS
        Context.AddSetEvent(9, new zpr.EventSource.EventContent { ByteData = value.ToByteString() });
        #endif
        data_ = value;
      }
    }

    /// <summary>Field number for the "test_map_two" field.</summary>
    public const int TestMapTwoFieldNumber = 10;
    private static readonly pbc::MapField<int, string>.Codec _map_testMapTwo_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForString(18), 82);
    internal class TestMapTwoMapConverter : EventMapConverter<int, string> {
      public override ByteString GetKeyValue(int key, string value, bool skipValue = false) {
        using (var memStream = new MemoryStream()) {
          var dataStream = new CodedOutputStream(memStream);
          dataStream.WriteInt32(key);
          if(!skipValue) dataStream.WriteString(value);
          dataStream.Flush();
          return ByteString.CopyFrom(memStream.ToArray());
        }
      }
      public override KeyValuePair<int, string> GetItem(ByteString data, bool skipValue = false) {
        var dataStream = data.CreateCodedInput();
        var realKeytestMapTwo = dataStream.ReadInt32();
        if (skipValue) {
          return new KeyValuePair<int, string>(realKeytestMapTwo, default(string));
        }
        else {
          var realValuetestMapTwo = dataStream.ReadString();
          return new KeyValuePair<int, string>(realKeytestMapTwo, realValuetestMapTwo);
        }
      }
    }
    private static readonly EventMapConverter<int, string> testMapTwoMapConverter = new TestMapTwoMapConverter();
    private readonly EventMapField<int, string> testMapTwo_ = new EventMapField<int, string>(testMapTwoMapConverter);
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EventMapField<int, string> TestMapTwo {
      get { return testMapTwo_; }
    }

    /// <summary>Field number for the "test_non_message" field.</summary>
    public const int TestNonMessageFieldNumber = 11;
    private global::Com.Zynga.Runtime.Protobuf.TestMessage testNonMessage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Zynga.Runtime.Protobuf.TestMessage TestNonMessage {
      get { return testNonMessage_; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(11, new zpr.EventSource.EventContent { ByteData = value.ToByteString() });
        #endif
        testNonMessage_ = value;
      }
    }

    /// <summary>Field number for the "test_string_no_checksum" field.</summary>
    public const int TestStringNoChecksumFieldNumber = 12;
    private string testStringNoChecksum_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TestStringNoChecksum {
      get { return testStringNoChecksum_; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(12, new zpr.EventSource.EventContent { StringData = pb::ProtoPreconditions.CheckNotNull(value, "value") });
        #endif
        testStringNoChecksum_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "test_bytes_field" field.</summary>
    public const int TestBytesFieldFieldNumber = 13;
    private pb::ByteString testBytesField_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString TestBytesField {
      get { return testBytesField_; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(13, new zpr.EventSource.EventContent { ByteData = pb::ProtoPreconditions.CheckNotNull(value, "value") });
        #endif
        testBytesField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "date" field.</summary>
    public const int DateFieldNumber = 14;
    private global::Google.Protobuf.WellKnownTypes.Timestamp date_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Date {
      get { return date_; }
      set {
        #if !DISABLE_EVENTS
        Context.AddSetEvent(14, new zpr.EventSource.EventContent { ByteData = value.ToByteString() });
        #endif
        date_ = value;
      }
    }

    public object testOneof_;
    /// <summary>Enum of possible cases for the "testOneof" oneof.</summary>
    public enum TestOneofOneofCase {
      None = 0,
      Foo = 2,
      Internal = 3,
    }
    public TestOneofOneofCase testOneofCase_ = TestOneofOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestOneofOneofCase TestOneofCase {
      get { return testOneofCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearTestOneof() {
      testOneofCase_ = TestOneofOneofCase.None;
      testOneof_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EventTest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EventTest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EventId != other.EventId) return false;
      if (Foo != other.Foo) return false;
      if (!object.Equals(Internal, other.Internal)) return false;
      if (TestEvent != other.TestEvent) return false;
      if(!testPrim_.Equals(other.testPrim_)) return false;
      if(!testMessage_.Equals(other.testMessage_)) return false;
      if(!testEnum_.Equals(other.testEnum_)) return false;
      if (!testMap_.Equals(other.testMap_)) return false;
      if (!object.Equals(Data, other.Data)) return false;
      if (!testMapTwo_.Equals(other.testMapTwo_)) return false;
      if (!object.Equals(TestNonMessage, other.TestNonMessage)) return false;
      if (TestStringNoChecksum != other.TestStringNoChecksum) return false;
      if (TestBytesField != other.TestBytesField) return false;
      if (!object.Equals(Date, other.Date)) return false;
      if (TestOneofCase != other.TestOneofCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EventId.Length != 0) hash ^= EventId.GetHashCode();
      if (testOneofCase_ == TestOneofOneofCase.Foo) hash ^= Foo.GetHashCode();
      if (testOneofCase_ == TestOneofOneofCase.Internal) hash ^= Internal.GetHashCode();
      if (TestEvent != 0) hash ^= TestEvent.GetHashCode();
      hash ^= testPrim_.GetHashCode();
      hash ^= testMessage_.GetHashCode();
      hash ^= testEnum_.GetHashCode();
      hash ^= testMap_.GetHashCode();
      if (data_ != null) hash ^= Data.GetHashCode();
      hash ^= testMapTwo_.GetHashCode();
      if (testNonMessage_ != null) hash ^= TestNonMessage.GetHashCode();
      if (TestStringNoChecksum.Length != 0) hash ^= TestStringNoChecksum.GetHashCode();
      if (TestBytesField.Length != 0) hash ^= TestBytesField.GetHashCode();
      if (date_ != null) hash ^= Date.GetHashCode();
      hash ^= (int) testOneofCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    public void GetChecksum(BinaryWriter inWriter) {
      if (EventId.Length != 0) inWriter.Write(EventId);
      if (testOneofCase_ == TestOneofOneofCase.Foo) inWriter.Write(Foo);
      if (testOneofCase_ == TestOneofOneofCase.Internal) Internal.GetChecksum(inWriter);
      if (TestEvent != 0) inWriter.Write((int)testEvent_);
      foreach (var item in testPrim_) {
          inWriter.Write(item);
      }
      foreach (var item in testMessage_) {
          item.GetChecksum(inWriter);
      }
      foreach (var item in testEnum_) {
          inWriter.Write((int)item);
      }
      foreach (var item in testMap_) {
          inWriter.Write(item.Key);
          item.Value.GetChecksum(inWriter);
      }
      if (data_ != null) Data.GetChecksum(inWriter);
      foreach (var item in testMapTwo_) {
          inWriter.Write(item.Key);
          inWriter.Write(item.Value);
      }
      if (testNonMessage_ != null) TestNonMessage.GetChecksum(inWriter);
      if (TestBytesField.Length != 0) inWriter.Write(testBytesField_.ToByteArray());
      if (date_ != null) Date.GetChecksum(inWriter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EventId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EventId);
      }
      if (testOneofCase_ == TestOneofOneofCase.Foo) {
        output.WriteRawTag(18);
        output.WriteString(Foo);
      }
      if (testOneofCase_ == TestOneofOneofCase.Internal) {
        output.WriteRawTag(26);
        output.WriteMessage(Internal);
      }
      if (TestEvent != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) TestEvent);
      }
      testPrim_.WriteTo(output, _repeated_testPrim_codec);
      testMessage_.WriteTo(output, _repeated_testMessage_codec);
      testEnum_.WriteTo(output, _repeated_testEnum_codec);
      testMap_.WriteTo(output, _map_testMap_codec);
      if (data_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Data);
      }
      testMapTwo_.WriteTo(output, _map_testMapTwo_codec);
      if (testNonMessage_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(TestNonMessage);
      }
      if (TestStringNoChecksum.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(TestStringNoChecksum);
      }
      if (TestBytesField.Length != 0) {
        output.WriteRawTag(106);
        output.WriteBytes(TestBytesField);
      }
      if (date_ != null) {
        output.WriteRawTag(114);
        output.WriteMessage(Date);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EventId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EventId);
      }
      if (testOneofCase_ == TestOneofOneofCase.Foo) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Foo);
      }
      if (testOneofCase_ == TestOneofOneofCase.Internal) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Internal);
      }
      if (TestEvent != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TestEvent);
      }
      size += testPrim_.CalculateSize(_repeated_testPrim_codec);
      size += testMessage_.CalculateSize(_repeated_testMessage_codec);
      size += testEnum_.CalculateSize(_repeated_testEnum_codec);
      size += testMap_.CalculateSize(_map_testMap_codec);
      if (data_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Data);
      }
      size += testMapTwo_.CalculateSize(_map_testMapTwo_codec);
      if (testNonMessage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TestNonMessage);
      }
      if (TestStringNoChecksum.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TestStringNoChecksum);
      }
      if (TestBytesField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(TestBytesField);
      }
      if (date_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Date);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EventTest other) {
      if (other == null) {
        return;
      }
      if (other.EventId.Length != 0) {
        EventId = other.EventId;
      }
      if (other.TestEvent != 0) {
        TestEvent = other.TestEvent;
      }
      testPrim_.Add(other.testPrim_);
      testMessage_.Add(other.testMessage_);
      testEnum_.Add(other.testEnum_);
      testMap_.Add(other.testMap_);
      if (other.data_ != null) {
        if (data_ == null) {
          data_ = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest();
        }
        Data.MergeFrom(other.Data);
      }
      testMapTwo_.Add(other.testMapTwo_);
      if (other.testNonMessage_ != null) {
        if (testNonMessage_ == null) {
          testNonMessage_ = new global::Com.Zynga.Runtime.Protobuf.TestMessage();
        }
        TestNonMessage.MergeFrom(other.TestNonMessage);
      }
      if (other.TestStringNoChecksum.Length != 0) {
        TestStringNoChecksum = other.TestStringNoChecksum;
      }
      if (other.TestBytesField.Length != 0) {
        TestBytesField = other.TestBytesField;
      }
      if (other.date_ != null) {
        if (date_ == null) {
          date_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Date.MergeFrom(other.Date);
      }
      switch (other.TestOneofCase) {
        case TestOneofOneofCase.Foo:
          Foo = other.Foo;
          break;
        case TestOneofOneofCase.Internal:
          if (Internal == null) {
            Internal = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage();
          }
          Internal.MergeFrom(other.Internal);
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            EventId = input.ReadString();
            break;
          }
          case 18: {
            Foo = input.ReadString();
            break;
          }
          case 26: {
            global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage subBuilder = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage();
            if (testOneofCase_ == TestOneofOneofCase.Internal) {
              subBuilder.MergeFrom(Internal);
            }
            input.ReadMessage(subBuilder);
            Internal = subBuilder;
            break;
          }
          case 32: {
            testEvent_ = (global::Com.Zynga.Runtime.Protobuf.EnumTest) input.ReadEnum();
            break;
          }
          case 42:
          case 40: {
            testPrim_.AddEntriesFrom(input, _repeated_testPrim_codec);
            break;
          }
          case 50: {
            testMessage_.AddEntriesFrom(input, _repeated_testMessage_codec);
            break;
          }
          case 58:
          case 56: {
            testEnum_.AddEntriesFrom(input, _repeated_testEnum_codec);
            break;
          }
          case 66: {
            testMap_.AddEntriesFrom(input, _map_testMap_codec);
            break;
          }
          case 74: {
            if (data_ == null) {
              data_ = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest();
            }
            input.ReadMessage(data_);
            break;
          }
          case 82: {
            testMapTwo_.AddEntriesFrom(input, _map_testMapTwo_codec);
            break;
          }
          case 90: {
            if (testNonMessage_ == null) {
              testNonMessage_ = new global::Com.Zynga.Runtime.Protobuf.TestMessage();
            }
            input.ReadMessage(testNonMessage_);
            break;
          }
          case 98: {
            TestStringNoChecksum = input.ReadString();
            break;
          }
          case 106: {
            TestBytesField = input.ReadBytes();
            break;
          }
          case 114: {
            if (date_ == null) {
              date_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(date_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the EventTest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// must flag internal message as event_sourced
      /// </summary>
      public sealed partial class NestedMessage : zpr::EventRegistry, pb::IMessage<NestedMessage> {
        private static readonly pb::MessageParser<NestedMessage> _parser = new pb::MessageParser<NestedMessage>(() => new NestedMessage());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<NestedMessage> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Zynga.Runtime.Protobuf.EventTest.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public NestedMessage() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public NestedMessage(NestedMessage other) : this() {
          data_ = other.data_;
          dataTwo_ = other.dataTwo_ != null ? other.DataTwo.Clone() : null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public NestedMessage Clone() {
          return new NestedMessage(this);
        }

        public static bool IsEventSourced = true;

        public override void SetParent(EventContext parent, EventPath path) {
          base.SetParent(parent, path);
        }
        /// <summary>Field number for the "data" field.</summary>
        public const int DataFieldNumber = 1;
        private int data_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Data {
          get { return data_; }
          set {
            #if !DISABLE_EVENTS
            Context.AddSetEvent(1, new zpr.EventSource.EventContent { I32 = value });
            #endif
            data_ = value;
          }
        }

        /// <summary>Field number for the "dataTwo" field.</summary>
        public const int DataTwoFieldNumber = 2;
        private global::Com.Zynga.Runtime.Protobuf.TestTwoMessage dataTwo_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Com.Zynga.Runtime.Protobuf.TestTwoMessage DataTwo {
          get { return dataTwo_; }
          set {
            if(dataTwo_ != null) dataTwo_.ClearParent();
            value.SetParent(Context, new EventPath(Context.Path, 2));
            #if !DISABLE_EVENTS
            Context.AddSetEvent(2, new zpr.EventSource.EventContent { ByteData = value.ToByteString() });
            #endif
            dataTwo_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as NestedMessage);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(NestedMessage other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Data != other.Data) return false;
          if (!object.Equals(DataTwo, other.DataTwo)) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Data != 0) hash ^= Data.GetHashCode();
          if (dataTwo_ != null) hash ^= DataTwo.GetHashCode();
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void GetChecksum(BinaryWriter inWriter) {
          if (Data != 0) inWriter.Write(Data);
          if (dataTwo_ != null) DataTwo.GetChecksum(inWriter);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Data != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Data);
          }
          if (dataTwo_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(DataTwo);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Data != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Data);
          }
          if (dataTwo_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataTwo);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(NestedMessage other) {
          if (other == null) {
            return;
          }
          if (other.Data != 0) {
            Data = other.Data;
          }
          if (other.dataTwo_ != null) {
            if (dataTwo_ == null) {
              dataTwo_ = new global::Com.Zynga.Runtime.Protobuf.TestTwoMessage();
            }
            DataTwo.MergeFrom(other.DataTwo);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 8: {
                Data = input.ReadInt32();
                break;
              }
              case 18: {
                if (dataTwo_ == null) {
                  dataTwo_ = new global::Com.Zynga.Runtime.Protobuf.TestTwoMessage();
                }
                input.ReadMessage(dataTwo_);
                break;
              }
            }
          }
        }

        public override bool ApplyEvent(zpr.EventSource.EventData e, int pathIndex) {
            if (e.Path.Count == 0) {
              this.MergeFrom(e.Set.ByteData);
              return true;
            }
            switch (e.Path[pathIndex]) {
              case 1: {
                data_ = e.Set.I32;
              }
              break;
              case 2: {
                if (e.Path.Count - 1 != pathIndex) {
                  if (dataTwo_ == null) dataTwo_ = new global::Com.Zynga.Runtime.Protobuf.TestTwoMessage();
                  (dataTwo_ as zpr::EventRegistry)?.ApplyEvent(e, pathIndex + 1);
                } else {
                  dataTwo_  = global::Com.Zynga.Runtime.Protobuf.TestTwoMessage.Parser.ParseFrom(e.Set.ByteData);
                }
              }
              break;
              default: 
                return false;
              break;
            }
          return true;
        }

        public zpr.EventSource.EventSourceRoot GenerateSnapshot() {
          var er = new zpr.EventSource.EventSourceRoot();
          var setEvent = new zpr.EventSource.EventData {
            Set = new zpr.EventSource.EventContent {
              ByteData = this.ToByteString()
            }
          };
          er.Events.Add(setEvent);
          return er;
        }

      }

      public sealed partial class EventOneofTest : zpr::EventRegistry, pb::IMessage<EventOneofTest> {
        private static readonly pb::MessageParser<EventOneofTest> _parser = new pb::MessageParser<EventOneofTest>(() => new EventOneofTest());
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<EventOneofTest> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Com.Zynga.Runtime.Protobuf.EventTest.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public EventOneofTest() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public EventOneofTest(EventOneofTest other) : this() {
          switch (other.BodyCase) {
            case BodyOneofCase.Foo:
              Foo = other.Foo;
              break;
            case BodyOneofCase.Internal:
              Internal = other.Internal.Clone();
              break;
          }

        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public EventOneofTest Clone() {
          return new EventOneofTest(this);
        }

        public static bool IsEventSourced = true;

        public override void SetParent(EventContext parent, EventPath path) {
          base.SetParent(parent, path);
        }
        /// <summary>Field number for the "foo" field.</summary>
        public const int FooFieldNumber = 1;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Foo {
          get { return bodyCase_ == BodyOneofCase.Foo ? (string) body_ : ""; }
          set {
            #if !DISABLE_EVENTS
            Context.AddSetEvent(1, new zpr.EventSource.EventContent { StringData = pb::ProtoPreconditions.CheckNotNull(value, "value") });
            #endif
            body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            bodyCase_ = BodyOneofCase.Foo;
          }
        }

        /// <summary>Field number for the "internal" field.</summary>
        public const int InternalFieldNumber = 2;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage Internal {
          get { return bodyCase_ == BodyOneofCase.Internal ? (global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage) body_ : null; }
          set {
            #if !DISABLE_EVENTS
            Context.AddSetEvent(2, new zpr.EventSource.EventContent { ByteData = value.ToByteString() });
            #endif
            body_ = value;
            bodyCase_ = value == null ? BodyOneofCase.None : BodyOneofCase.Internal;
          }
        }

        public object body_;
        /// <summary>Enum of possible cases for the "body" oneof.</summary>
        public enum BodyOneofCase {
          None = 0,
          Foo = 1,
          Internal = 2,
        }
        public BodyOneofCase bodyCase_ = BodyOneofCase.None;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public BodyOneofCase BodyCase {
          get { return bodyCase_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void ClearBody() {
          bodyCase_ = BodyOneofCase.None;
          body_ = null;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as EventOneofTest);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(EventOneofTest other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Foo != other.Foo) return false;
          if (!object.Equals(Internal, other.Internal)) return false;
          if (BodyCase != other.BodyCase) return false;
          return true;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (bodyCase_ == BodyOneofCase.Foo) hash ^= Foo.GetHashCode();
          if (bodyCase_ == BodyOneofCase.Internal) hash ^= Internal.GetHashCode();
          hash ^= (int) bodyCase_;
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        public void GetChecksum(BinaryWriter inWriter) {
          if (bodyCase_ == BodyOneofCase.Foo) inWriter.Write(Foo);
          if (bodyCase_ == BodyOneofCase.Internal) Internal.GetChecksum(inWriter);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (bodyCase_ == BodyOneofCase.Foo) {
            output.WriteRawTag(10);
            output.WriteString(Foo);
          }
          if (bodyCase_ == BodyOneofCase.Internal) {
            output.WriteRawTag(18);
            output.WriteMessage(Internal);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (bodyCase_ == BodyOneofCase.Foo) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Foo);
          }
          if (bodyCase_ == BodyOneofCase.Internal) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Internal);
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(EventOneofTest other) {
          if (other == null) {
            return;
          }
          switch (other.BodyCase) {
            case BodyOneofCase.Foo:
              Foo = other.Foo;
              break;
            case BodyOneofCase.Internal:
              if (Internal == null) {
                Internal = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage();
              }
              Internal.MergeFrom(other.Internal);
              break;
          }

        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                input.SkipLastField();
                break;
              case 10: {
                Foo = input.ReadString();
                break;
              }
              case 18: {
                global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage subBuilder = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage();
                if (bodyCase_ == BodyOneofCase.Internal) {
                  subBuilder.MergeFrom(Internal);
                }
                input.ReadMessage(subBuilder);
                Internal = subBuilder;
                break;
              }
            }
          }
        }

        public override bool ApplyEvent(zpr.EventSource.EventData e, int pathIndex) {
            if (e.Path.Count == 0) {
              this.MergeFrom(e.Set.ByteData);
              return true;
            }
            switch (e.Path[pathIndex]) {
              case 1: {
                body_ = pb::ProtoPreconditions.CheckNotNull(e.Set.StringData, "value");
                bodyCase_ = BodyOneofCase.Foo;
              }
              break;
              case 2: {
                body_  = global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage.Parser.ParseFrom(e.Set.ByteData);
                bodyCase_ = body_ == null ? BodyOneofCase.None : BodyOneofCase.Internal;
              }
              break;
              default: 
                return false;
              break;
            }
          return true;
        }

        public zpr.EventSource.EventSourceRoot GenerateSnapshot() {
          var er = new zpr.EventSource.EventSourceRoot();
          var setEvent = new zpr.EventSource.EventData {
            Set = new zpr.EventSource.EventContent {
              ByteData = this.ToByteString()
            }
          };
          er.Events.Add(setEvent);
          return er;
        }

      }

    }
    #endregion

    public override bool ApplyEvent(zpr.EventSource.EventData e, int pathIndex) {
        if (e.Path.Count == 0) {
          this.MergeFrom(e.Set.ByteData);
          return true;
        }
        switch (e.Path[pathIndex]) {
          case 1: {
            eventId_ = e.Set.StringData;
          }
          break;
          case 2: {
            testOneof_ = pb::ProtoPreconditions.CheckNotNull(e.Set.StringData, "value");
            testOneofCase_ = TestOneofOneofCase.Foo;
          }
          break;
          case 3: {
            if (e.Path.Count - 1 != pathIndex) {
              if (testOneof_ == null) testOneof_ = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage();
              (testOneof_  as zpr::EventRegistry)?.ApplyEvent(e, pathIndex + 1);
            } else {
              testOneof_   = global::Com.Zynga.Runtime.Protobuf.EventTest.Types.NestedMessage.Parser.ParseFrom(e.Set.ByteData);
            }
            testOneofCase_ = testOneof_ == null ? TestOneofOneofCase.None : TestOneofOneofCase.Internal;
          }
          break;
          case 4: {
            testEvent_ = (global::Com.Zynga.Runtime.Protobuf.EnumTest)e.Set.U32;
          }
          break;
          case 5: {
            testPrim_.ApplyEvent(e.ListEvent);
          }
          break;
          case 6: {
            testMessage_.ApplyEvent(e.ListEvent);
          }
          break;
          case 7: {
            testEnum_.ApplyEvent(e.ListEvent);
          }
          break;
          case 8: {
            testMap_.ApplyEvent(e.MapEvent);
          }
          break;
          case 9: {
            if (e.Path.Count - 1 != pathIndex) {
              if (data_ == null) data_ = new global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest();
              (data_ as zpr::EventRegistry)?.ApplyEvent(e, pathIndex + 1);
            } else {
              data_  = global::Com.Zynga.Runtime.Protobuf.EventTest.Types.EventOneofTest.Parser.ParseFrom(e.Set.ByteData);
            }
          }
          break;
          case 10: {
            testMapTwo_.ApplyEvent(e.MapEvent);
          }
          break;
          case 11: {
            testNonMessage_  = global::Com.Zynga.Runtime.Protobuf.TestMessage.Parser.ParseFrom(e.Set.ByteData);
          }
          break;
          case 12: {
            testStringNoChecksum_ = e.Set.StringData;
          }
          break;
          case 13: {
            testBytesField_ = e.Set.ByteData;
          }
          break;
          case 14: {
            date_  = global::Google.Protobuf.WellKnownTypes.Timestamp.Parser.ParseFrom(e.Set.ByteData);
          }
          break;
          default: 
            return false;
          break;
        }
      return true;
    }

    public zpr.EventSource.EventSourceRoot GenerateSnapshot() {
      var er = new zpr.EventSource.EventSourceRoot();
      var setEvent = new zpr.EventSource.EventData {
        Set = new zpr.EventSource.EventContent {
          ByteData = this.ToByteString()
        }
      };
      er.Events.Add(setEvent);
      return er;
    }

  }

  #endregion

}

#endregion Designer generated code
