// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test/struct_test.proto
#pragma warning disable 1591, 0612, 3021, 162
#region Designer generated code

using System;
using System.IO;
using System.Collections.Generic;
using Google.Protobuf;
using global::Zynga.Protobuf.Runtime;
using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
using zpr = global::Zynga.Protobuf.Runtime;
namespace Com.Zynga.Runtime.Protobuf {

  /// <summary>Holder for reflection information generated from test/struct_test.proto</summary>
  public static partial class StructTestReflection {

    #region Descriptor
    /// <summary>File descriptor for test/struct_test.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StructTestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ0ZXN0L3N0cnVjdF90ZXN0LnByb3RvEhpjb20uenluZ2EucnVudGltZS5w",
            "cm90b2J1ZhoSZXZlbnRfcGx1Z2luLnByb3RvInMKClRlc3RTdHJ1Y3QSEgoE",
            "bG9uZxgDIAEoA1IEbG9uZxJLCgZuZXN0ZWQYASABKAsyMy5jb20uenluZ2Eu",
            "cnVudGltZS5wcm90b2J1Zi5UZXN0TWVzc2FnZU5lc3RlZFN0cnVjdFIGbmVz",
            "dGVkOgTguB4BIk8KF1Rlc3RNZXNzYWdlTmVzdGVkU3RydWN0EjQKAWEYASAB",
            "KAsyJi5jb20uenluZ2EucnVudGltZS5wcm90b2J1Zi5UZXN0U3RydWN0UgFh",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Zynga.Protobuf.EventSource.EventPluginReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Zynga.Runtime.Protobuf.TestStruct), global::Com.Zynga.Runtime.Protobuf.TestStruct.Parser, new[]{ "Long", "Nested" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Com.Zynga.Runtime.Protobuf.TestMessageNestedStruct), global::Com.Zynga.Runtime.Protobuf.TestMessageNestedStruct.Parser, new[]{ "A" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public partial struct TestStruct : pb::IMessage<TestStruct> {
    private static readonly pb::MessageParser<TestStruct> _parser = new pb::MessageParser<TestStruct>(() => new TestStruct());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestStruct> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Zynga.Runtime.Protobuf.StructTestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestStruct(TestStruct other) : this() {
      long_ = other.long_;
      nested_ = other.nested_ != null ? other.Nested.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestStruct Clone() {
      return new TestStruct(this);
    }

    public static bool IsEventSourced = false;

    /// <summary>Field number for the "long" field.</summary>
    public const int LongFieldNumber = 3;
    private long long_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Long {
      get { return long_; }
      set {
        long_ = value;
      }
    }

    /// <summary>Field number for the "nested" field.</summary>
    public const int NestedFieldNumber = 1;
    private global::Com.Zynga.Runtime.Protobuf.TestMessageNestedStruct nested_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Zynga.Runtime.Protobuf.TestMessageNestedStruct Nested {
      get { return nested_; }
      set {
        nested_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestStruct other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Long != other.Long) return false;
      if (!object.Equals(Nested, other.Nested)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Long != 0L) hash ^= Long.GetHashCode();
      if (nested_ != null) hash ^= Nested.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (nested_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Nested);
      }
      if (Long != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Long);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Long != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Long);
      }
      if (nested_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Nested);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestStruct other) {
      if (other.Long != 0L) {
        long_ = other.Long;
      }
      if (other.nested_ != null) {
        if (nested_ == null) {
          nested_ = new global::Com.Zynga.Runtime.Protobuf.TestMessageNestedStruct();
        }
        Nested.MergeFrom(other.Nested);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (nested_ == null) {
              nested_ = new global::Com.Zynga.Runtime.Protobuf.TestMessageNestedStruct();
            }
            input.ReadMessage(nested_);
            break;
          }
          case 24: {
            long_ = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class TestMessageNestedStruct : pb::IMessage<TestMessageNestedStruct> {
    private static readonly pb::MessageParser<TestMessageNestedStruct> _parser = new pb::MessageParser<TestMessageNestedStruct>(() => new TestMessageNestedStruct());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<TestMessageNestedStruct> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Com.Zynga.Runtime.Protobuf.StructTestReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestMessageNestedStruct() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestMessageNestedStruct(TestMessageNestedStruct other) : this() {
      a_ = other.A.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public TestMessageNestedStruct Clone() {
      return new TestMessageNestedStruct(this);
    }

    public static bool IsEventSourced = false;

    /// <summary>Field number for the "a" field.</summary>
    public const int AFieldNumber = 1;
    private global::Com.Zynga.Runtime.Protobuf.TestStruct a_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Com.Zynga.Runtime.Protobuf.TestStruct A {
      get { return a_; }
      set {
        a_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as TestMessageNestedStruct);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(TestMessageNestedStruct other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(A, other.A)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= A.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      output.WriteRawTag(10);
      output.WriteMessage(A);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(A);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(TestMessageNestedStruct other) {
      if (other == null) {
        return;
      }
      A.MergeFrom(other.A);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            a_ = new global::Com.Zynga.Runtime.Protobuf.TestStruct();
            a_.MergeFrom(input);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
